name: Build and Test

on: 
  pull_request:
    branches: 
      - master
  workflow_dispatch:

jobs:
  build:
    name: Build Docker image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1
        
      - name: Build Docker image
        id: build
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./backend/Dockerfile
          push: false  # Build the image but don't push yet
          tags: testimage

      - name: Run container from built image
        run: docker run -d --name test-container testimage

      - name: Run tests inside container
        run: |
          docker exec test-container dotnet test --no-build --verbosity normal
  push:
    name: Push Docker image
    runs-on: ubuntu-latest
    needs: test  # Only push if tests pass
    steps:
      - name: Echo something
        run: echo "hello"