name: Build and Test

on: 
  pull_request:
    branches: 
      - master
  workflow_dispatch:

jobs:
  build:
    name: Build Docker image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1
        
      - name: Build Docker image
        id: build-test
        uses: docker/build-push-action@v2
        with:
          context: ./backend
          file: ./backend/Dockerfile.test
          push: false  # Build the image but don't push yet
          # Load image into docker (if no load happens, the image won't be available in the next step)
          load: true
          tags: test-image

      - name: Run container from built image
        run: docker run -d --name test-container test-image

      - name: Run tests inside container
        run: |
          docker exec test-container dotnet test --no-build --verbosity normal ./backend.Tests/backend.Tests.csproj
  push:
    name: Push Docker image
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Echo something
        run: echo "hello"
